[package]
name = "ruda-store-safetensors-tests"
version = "0.21.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "ruda-store-safetensors-tests"
repository = "https://github.com/shuqi2077/RUDA"

[dev-dependencies.ruda-model]
default-features = false
features = [ "default",]
path = "../../ruda-model"
version = "0.21.0"

[dev-dependencies.ruda-nn]
default-features = false
features = [ "default",]
path = "../../ruda-nn"
version = "0.21.0"

[dev-dependencies.ruda-optim]
default-features = false
features = [ "default",]
path = "../../ruda-optim"
version = "0.21.0"

[dev-dependencies.ruda-tensor-host]
path = "../../ruda-tensor-host"
version = "0.21.0"
default-features = false
features = [ "default",]

[dev-dependencies.ruda-autodiff]
default-features = false
features = [ "std", "tracing",]
path = "../../ruda-autodiff"
version = "0.21.0"

[dev-dependencies.ruda-kernel]
path = "../../ruda-kernel"
version = "0.1.0"
default-features = false
features = [ "frontend-std", "frontend-tracing",]

[dev-dependencies.ruda-store]
default-features = false
features = [ "default", "std", "safetensors",]
path = ".."
version = "0.21.0"

[dev-dependencies.serde]
version = "1.0.228"
default-features = false
features = [ "derive", "alloc",]

[dev-dependencies.float-cmp]
version = "0.10.0"
features = []

[dev-dependencies.ruda-tensor]
path = "../../ruda-tensor"
version = "0.21.0"
default-features = false
features = [ "api",]
