[workspace]
default-members = ["ruTENSOR", "ruda-tensor-wgpu", "ruda-tensor-rocm", "ruCCL", "ruda-communication", "ruda-tensor-host", "ruRAND/host", "ruPRIM/host", "ruDNN/host", "ruBLAS/host", "ruFFT/host", "ruda-store/pytorch-tests", "ruda-store/safetensors-tests", "ruda-store", "ruda-optim", "ruda-nn", "ruda-model", "ruda-io", "ruda-model-macros", "ruda-model-codegen", "ruda-tensor-device", "ruda-fusion", "ruda-autodiff", "ruda-tensor-config", "ruda-tensor", "ruda-core", "ruda-ir-macros", "ruda-compiler", "ruda-kernel-macros", "ruda-kernel", "ruda", "ruPRIM", "ruBLAS", "ruFFT", "ruDNN", "ruRAND", "ruda-test-utils", "ruSPARSE"]
members = ["ruda-hip-sys", "ruTENSOR", "ruLLM", "ruda-dataset", "ruda-tensor-router", "ruda-tensor-remote", "ruda-tensor-tch", "ruda-tensor-wgpu", "ruda-tensor-rocm", "ruCCL", "ruda-communication", "ruda-tensor-host", "ruRAND/host", "ruPRIM/host", "ruDNN/host", "ruBLAS/host", "ruFFT/host", "ruda-store/pytorch-tests", "ruda-store/safetensors-tests", "ruda-store", "ruda-optim", "ruda-nn", "ruda-model", "ruda-io", "ruda-model-macros", "ruda-model-codegen", "ruda-tensor-device", "ruda-fusion", "ruda-autodiff", "ruda-tensor-config", "ruda-tensor", "ruda-test-runtime", "ruda-driver-wgpu", "ruda-driver-cpu", "ruda-driver-cuda", "ruda-driver-hip", "ruda-core", "ruda-ir-macros", "ruda-compiler", "ruda-kernel-macros", "ruda-kernel", "ruda", "ruPRIM", "ruBLAS", "ruFFT", "ruDNN", "ruRAND", "ruda-test-utils", "ruSPARSE"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.dev.package.ruda-store]
opt-level = 3
