[package]
name = "ruda"
version = "0.1.19"
edition.workspace = true
readme = "README.md"
description = "Ruda GPU kernel API and portable runtime with CUDA, HIP and WGPU backends."
license-file = "../LICENSE"
repository = "https://github.com/shuqi2077/RUDA"

[features]
default = ["runtime-default"]
cuda = ["kernel", "dep:ruda-driver-cuda"]
hip = ["kernel", "dep:ruda-driver-hip"]
wgpu = ["kernel", "dep:ruda-driver-wgpu"]
direct-ptx = ["cuda", "ruda-driver-cuda/direct-ptx"]
kernel = ["runtime-default", "dep:ruda-kernel"]
runtime = ["ruda-runtime/runtime"]
runtime-autotune-checks = ["runtime", "ruda-runtime/runtime-autotune-checks"]
runtime-channel-cell = ["runtime", "ruda-runtime/runtime-channel-cell"]
runtime-channel-mpsc = ["runtime", "ruda-runtime/runtime-channel-mpsc"]
runtime-channel-mutex = ["runtime", "ruda-runtime/runtime-channel-mutex"]
runtime-default = ["runtime", "runtime-std", "runtime-channel-mutex", "runtime-channel-mpsc", "runtime-channel-cell", "runtime-storage-bytes", "ruda-runtime/runtime-default"]
runtime-exclusive-memory-only = ["runtime", "ruda-runtime/runtime-exclusive-memory-only"]
runtime-profile-tracy = ["runtime", "ruda-runtime/runtime-profile-tracy"]
runtime-std = ["runtime", "toml", "dirs", "ruda-runtime/runtime-std"]
runtime-storage-bytes = ["runtime", "ruda-runtime/runtime-storage-bytes"]
runtime-tracing = ["runtime", "ruda-runtime/runtime-tracing"]
dirs = ["ruda-runtime/dirs"]
toml = ["ruda-runtime/toml"]

[dependencies]
ruda-runtime = { path = "../ruda-runtime", version = "0.1.8", default-features = false }
ruda-kernel = { path = "../ruda-kernel", version = "0.1.18", optional = true }
ruda-driver-cuda = { path = "../ruda-driver-cuda", version = "0.1.67", optional = true }
ruda-driver-hip = { path = "../ruda-driver-hip", version = "0.1.67", optional = true }
ruda-driver-wgpu = { path = "../ruda-driver-wgpu", version = "0.1.67", optional = true }

[dev-dependencies]
bytemuck = "1.16.1"
derive-new = { version = "0.7.0", default-features = false }
ruda-core = { path = "../ruda-core", version = "0.1.6", default-features = false, features = ["ir", "ir-serde", "tensor", "compiler", "communication"] }
rand = { version = "0.10.0", features = ["std_rng", "thread_rng"], default-features = false }
serial_test = "3.1.1"
test-log = { version = "^0.2", features = ["trace"], default-features = false }

[lints.rust]
unsafe_code = "deny"

[[test]]
name = "runtime"
path = "tests/runtime/integration_test.rs"
required-features = ["runtime"]

[[test]]
name = "stack_autotune"
path = "tests/runtime/stack_autotune.rs"
required-features = ["runtime", "runtime-std", "runtime-storage-bytes"]

[[bench]]
name = "runtime_memory"
path = "benches/runtime/dynamic.rs"
harness = false
required-features = ["runtime", "runtime-storage-bytes"]

[[example]]
name = "vector-add"
path = "examples/vector_add.rs"
required-features = ["kernel"]
